require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec
AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
  IgnoredPatterns:
    - '^#*'

Naming/FileName:
  Exclude:
    - 'lib/scim-kit.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
